version: '3.4'

services:

  nginx-edge:
    image: nginx-edge
    hostname: nginx-edge
    build: 
      context: ./nginx-edge
      dockerfile: Dockerfile
    networks:
      - lb-edge
    ports:
      - 80:80
    restart: always
    deploy:
     mode: replicated
     replicas: 1

  rabbit-mq:
    image: rabbit-mq
    hostname: rabbit-mq
    build: 
      context: ./rabbit-mq
      dockerfile: Dockerfile
    volumes:
      - rabbit-mq-vol:/var/lib/rabbitmq
    networks:
      - lb-edge
    ports:
      - 15672
      - 5672
      - 61613
      - 1883
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=core
    labels:
      - NAME=rabbit-mq
    restart: always
    deploy:
     mode: replicated
     replicas: 1

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer-adm:
    # image: portainer/portainer:alpine
    image: portainer/portainer-ce:2.0.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-adm-vol:/data
    environment:
      - VIRTUAL_HOST=portainer.localhost.com
      - VIRTUAL_PORT=9000
    ports:
      - 8000
    networks:
      - lb-edge
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


volumes:
  rabbit-mq-vol:
    driver: local
  portainer-adm-vol:
    driver: local

networks:
  lb-edge:
    driver: overlay
    attachable: true
  agent_network:
    driver: overlay
    attachable: true
