version: '3.4'

services:

  nginx-edge:
    image: nginx-edge
    hostname: nginx-edge
    build: 
      context: ./nginx-edge
      dockerfile: Dockerfile
    networks:
      - lb-edge
    ports:
      - 80:80
    restart: always
    deploy:
     mode: replicated
     replicas: 1

  rabbit-mq:
    image: rabbit-mq
    hostname: rabbit-mq
    build: 
      context: ./rabbit-mq
      dockerfile: Dockerfile
    volumes:
      - rabbit-mq-vol:/var/lib/rabbitmq
    networks:
      - lb-edge
    ports:
      - 15672:15672
      - 5672
      - 61613
      - 1883
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=core
    labels:
      - NAME=rabbit-mq
    restart: always
    deploy:
     mode: replicated
     replicas: 1

volumes:
  rabbit-mq-vol:
    driver: local

networks:
  lb-edge:
    driver: overlay
    attachable: true
